[package]
name = "oas"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "oas"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
openapiv3 = "0.3"
serde = "1"
serde_yaml = "0.8"
serde_json = "1"
