openapi: 3.0.0
info:
  title: Todo API
  description: |
    Hello world! This is a __Sample API__ for todo API
  version: 0.1.0
servers:
  - url: https://api.todo.mvc/v1
    description: Production server
  - url: http://localhost:4000/api/v1
    description: Local dev server
tags:
  - name: todos
  - name: todo

components:
  parameters:
    $ref: "./todo/params.yml"
  schemas:
    $ref: "./todo/schemas.yml"
  responses:
    $ref: "./todo/responses.yml"
  securitySchemes:
    token:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /todo/{todoId}:
    $ref: "./todo/services/todo.yml"
  /todos:
    $ref: "./todo/services/todos.yml"
